app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('game_solver/', include('game_solver.urls')),
    path('admin/', admin.site.urls),
]

game_solver/urls.py
from django.urls import path
from . import views

app_name = 'game_solver'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:game_id>/', views.detail, name='detail'),
]

game_solver/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Game(models.Model):
    creation_date = models.DateTimeField('date created', default=datetime.now)
    input = models.CharField(max_length=81)
    output = models.CharField(max_length=81, null=True, blank=True)

    def __str__(self):
        return self.input

game_solver/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


def validate_sudoku(value):
    if value.isdigit() == False:
        raise ValidationError(
            _('%(value)s contains digits other than 0-9'),
            params={'value': value},
        )
    if len(value) < 81:
        raise ValidationError(
            _('%(value)s is not enough characters to make a sudoku board'),
            params={'value': value},
        )

class NewSudokuForm(forms.Form):
    input = forms.CharField(label="Input:", max_length=81, validators=[validate_sudoku])

game_solver/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.urls import reverse

from .models import Game
from .solver import SudokuGame
from .forms import NewSudokuForm

def add_view_friendly_arrays_to_game(game):
    game.inputArray = [game.input[i:i+9].replace("0", " ") for i in range(0, len(game.input), 9)]
    game.outputArray = [game.output[i:i+9] for i in range(0, len(game.output), 9)]

def index(request):
    latest_games = Game.objects.filter(
        creation_date__lte=timezone.now()
    ).order_by('-creation_date')
    for game in latest_games:
        add_view_friendly_arrays_to_game(game)
    context = {'latest_games': latest_games}
    return render(request, 'game_solver/index.html', context)

def detail(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    add_view_friendly_arrays_to_game(game)
    return render(request, 'game_solver/detail.html', {'game': game})

def new(request):
    if request.method == 'POST':
        form = NewSudokuForm(request.POST)
        if form.is_valid():
            input = form.cleaned_data['input']
            play = SudokuGame(input)
            output = play.solveSudoku()
            game = Game.objects.create(input=input, output=output)
            return HttpResponseRedirect(reverse('game_solver:detail', args=(game.id,)))
    else:
        form = NewSudokuForm()
    return render(request, 'game_solver/new.html', {'form': form})

game_solver/templates/game_solver/detail.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'game_solver/style.css' %}">

<h2>Sudoku Detail View</h2>
<div class="flex-container">
	<div>
		<p>Original Puzzle</p>
	</div>
	<div>
		<p>Solution</p>
	</div>
</div>
<div class="flex-container">
	<div>
		<table class="detail">
		{% for line in game.inputArray %}
		<tr>
		{% for letter in line %}
		<td>
		{{letter}}
		</td>
		{% endfor %}
		</tr>
		{% endfor %}
		</table>
	</div>
	<div>
		<table class="detail">
		{% for line in game.outputArray %}
		<tr>
		{% for letter in line %}
		<td>
		{{letter}}
		</td>
		{% endfor %}
		</tr>
		{% endfor %}
		</table>
	</div>
</div>
<div>
	<a href="{% url 'game_solver:index' %}">
		<div class="button return-btn">Return to all games</div>
	</a>
</div>

game_solver/templates/game_solver/index.html
{% load static %}

<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'game_solver/style.css' %}">

<h1>A Super Fabulous Sudoku Solver</h1>
<p class="subtitle italic">Written by Elizabeth Locke</p>
<div class="main-button">
	<a href="{% url 'game_solver:new' %}">
		<button class="main-cta">
			Solve a New Puzzle
		</button>
	</a>
</div>
<h2>Recently Solved Puzzles</h2>
{% if latest_games %}
    <div class="games-list">
	<div class="flex-title">
		<div>Input Puzzle</div>
		<div>Solution</div>
		<div>Detail View</div>
	</div>
    {% for game in latest_games %}
    <div class="flex-container">
		<div>
			<table>
			{% for line in game.inputArray %}
			<tr>
			{% for letter in line %}
			<td>
			{{letter}}
			</td>
			{% endfor %}
			</tr>
			{% endfor %}
			</table>
		</div>
		<div>
			<table>
			{% for line in game.outputArray %}
			<tr>
			{% for letter in line %}
			<td>
			{{letter}}
			</td>
			{% endfor %}
			</tr>
			{% endfor %}
			</table>
		</div>
		<div>
			<a href="{% url 'game_solver:detail' game.id  %}">View Larger >></a>
		</div>
    </div>
    {% endfor %}
    </div>
{% else %}
    <p>You don't have any games yet.</p>
{% endif %}

game_solver/templates/game_solver/new.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'game_solver/style.css' %}">

<h2>Sudoku Game Solver</h2>
<p class="left">Instructions:</p>
<p class="left">
	Enter an unsolved sudoku puzzle as one line with every empty cell represented with a 0. For example
	<span class="integer-input">
		530070000600195000098000060800060003400803001700020006060000280000419005000080079
	</span>
</p>
<br/>
<form class= "left" method="post">
	{% csrf_token %}
	{{ form }}
	<input class="button" type="submit" value="Submit">
</form>
<div>
	<a href="{% url 'game_solver:index' %}">
		<< Return to all games
	</a>
</div>